# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BeaconConceptCategory(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, category: str=None, local_category: str=None, description: str=None, frequency: int=None):  # noqa: E501
        """BeaconConceptCategory - a model defined in Swagger

        :param category: The category of this BeaconConceptCategory.  # noqa: E501
        :type category: str
        :param local_category: The local_category of this BeaconConceptCategory.  # noqa: E501
        :type local_category: str
        :param description: The description of this BeaconConceptCategory.  # noqa: E501
        :type description: str
        :param frequency: The frequency of this BeaconConceptCategory.  # noqa: E501
        :type frequency: int
        """
        self.swagger_types = {
            'category': str,
            'local_category': str,
            'description': str,
            'frequency': int
        }

        self.attribute_map = {
            'category': 'category',
            'local_category': 'local_category',
            'description': 'description',
            'frequency': 'frequency'
        }

        self._category = category
        self._local_category = local_category
        self._description = description
        self._frequency = frequency

    @classmethod
    def from_dict(cls, dikt) -> 'BeaconConceptCategory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BeaconConceptCategory of this BeaconConceptCategory.  # noqa: E501
        :rtype: BeaconConceptCategory
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category(self) -> str:
        """Gets the category of this BeaconConceptCategory.

        human readable name (\"rdfs:label\")  # noqa: E501

        :return: The category of this BeaconConceptCategory.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this BeaconConceptCategory.

        human readable name (\"rdfs:label\")  # noqa: E501

        :param category: The category of this BeaconConceptCategory.
        :type category: str
        """

        self._category = category

    @property
    def local_category(self) -> str:
        """Gets the local_category of this BeaconConceptCategory.

        the locally designated CURIE of the concept category  # noqa: E501

        :return: The local_category of this BeaconConceptCategory.
        :rtype: str
        """
        return self._local_category

    @local_category.setter
    def local_category(self, local_category: str):
        """Sets the local_category of this BeaconConceptCategory.

        the locally designated CURIE of the concept category  # noqa: E501

        :param local_category: The local_category of this BeaconConceptCategory.
        :type local_category: str
        """

        self._local_category = local_category

    @property
    def description(self) -> str:
        """Gets the description of this BeaconConceptCategory.

        human readable name definition of the category  # noqa: E501

        :return: The description of this BeaconConceptCategory.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this BeaconConceptCategory.

        human readable name definition of the category  # noqa: E501

        :param description: The description of this BeaconConceptCategory.
        :type description: str
        """

        self._description = description

    @property
    def frequency(self) -> int:
        """Gets the frequency of this BeaconConceptCategory.

        the number of concept entries of the specified type in the beacon knowledge base  # noqa: E501

        :return: The frequency of this BeaconConceptCategory.
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: int):
        """Sets the frequency of this BeaconConceptCategory.

        the number of concept entries of the specified type in the beacon knowledge base  # noqa: E501

        :param frequency: The frequency of this BeaconConceptCategory.
        :type frequency: int
        """

        self._frequency = frequency
