# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BeaconKnowledgeMapObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, category: str=None, prefixes: List[str]=None):  # noqa: E501
        """BeaconKnowledgeMapObject - a model defined in Swagger

        :param category: The category of this BeaconKnowledgeMapObject.  # noqa: E501
        :type category: str
        :param prefixes: The prefixes of this BeaconKnowledgeMapObject.  # noqa: E501
        :type prefixes: List[str]
        """
        self.swagger_types = {
            'category': str,
            'prefixes': List[str]
        }

        self.attribute_map = {
            'category': 'category',
            'prefixes': 'prefixes'
        }

        self._category = category
        self._prefixes = prefixes

    @classmethod
    def from_dict(cls, dikt) -> 'BeaconKnowledgeMapObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BeaconKnowledgeMapObject of this BeaconKnowledgeMapObject.  # noqa: E501
        :rtype: BeaconKnowledgeMapObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category(self) -> str:
        """Gets the category of this BeaconKnowledgeMapObject.

        the concept semantic type of a statement object. This should be specified as Biolink concept semantic type names like gene, pathway, etc. (see [Biolink Model](https://biolink.github.io/biolink-model) for the full list of terms)   # noqa: E501

        :return: The category of this BeaconKnowledgeMapObject.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this BeaconKnowledgeMapObject.

        the concept semantic type of a statement object. This should be specified as Biolink concept semantic type names like gene, pathway, etc. (see [Biolink Model](https://biolink.github.io/biolink-model) for the full list of terms)   # noqa: E501

        :param category: The category of this BeaconKnowledgeMapObject.
        :type category: str
        """

        self._category = category

    @property
    def prefixes(self) -> List[str]:
        """Gets the prefixes of this BeaconKnowledgeMapObject.


        :return: The prefixes of this BeaconKnowledgeMapObject.
        :rtype: List[str]
        """
        return self._prefixes

    @prefixes.setter
    def prefixes(self, prefixes: List[str]):
        """Sets the prefixes of this BeaconKnowledgeMapObject.


        :param prefixes: The prefixes of this BeaconKnowledgeMapObject.
        :type prefixes: List[str]
        """

        self._prefixes = prefixes
