# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BeaconConcept(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, categories: List[str]=None, description: str=None):  # noqa: E501
        """BeaconConcept - a model defined in Swagger

        :param id: The id of this BeaconConcept.  # noqa: E501
        :type id: str
        :param name: The name of this BeaconConcept.  # noqa: E501
        :type name: str
        :param categories: The categories of this BeaconConcept.  # noqa: E501
        :type categories: List[str]
        :param description: The description of this BeaconConcept.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'categories': List[str],
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'categories': 'categories',
            'description': 'description'
        }

        self._id = id
        self._name = name
        self._categories = categories
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'BeaconConcept':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BeaconConcept of this BeaconConcept.  # noqa: E501
        :rtype: BeaconConcept
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this BeaconConcept.

        local object CURIE for the concept in the specified knowledge source database   # noqa: E501

        :return: The id of this BeaconConcept.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this BeaconConcept.

        local object CURIE for the concept in the specified knowledge source database   # noqa: E501

        :param id: The id of this BeaconConcept.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this BeaconConcept.

        canonical human readable name of the concept   # noqa: E501

        :return: The name of this BeaconConcept.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BeaconConcept.

        canonical human readable name of the concept   # noqa: E501

        :param name: The name of this BeaconConcept.
        :type name: str
        """

        self._name = name

    @property
    def categories(self) -> List[str]:
        """Gets the categories of this BeaconConcept.

        concept semantic type 'category'. Should be specified from the [Biolink Model](https://biolink.github.io/biolink-model).   # noqa: E501

        :return: The categories of this BeaconConcept.
        :rtype: List[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories: List[str]):
        """Sets the categories of this BeaconConcept.

        concept semantic type 'category'. Should be specified from the [Biolink Model](https://biolink.github.io/biolink-model).   # noqa: E501

        :param categories: The categories of this BeaconConcept.
        :type categories: List[str]
        """

        self._categories = categories

    @property
    def description(self) -> str:
        """Gets the description of this BeaconConcept.

        (optional) narrative concept definition   # noqa: E501

        :return: The description of this BeaconConcept.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this BeaconConcept.

        (optional) narrative concept definition   # noqa: E501

        :param description: The description of this BeaconConcept.
        :type description: str
        """

        self._description = description
