# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ExactMatchResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, within_domain: bool=None, has_exact_matches: List[str]=None):  # noqa: E501
        """ExactMatchResponse - a model defined in Swagger

        :param id: The id of this ExactMatchResponse.  # noqa: E501
        :type id: str
        :param within_domain: The within_domain of this ExactMatchResponse.  # noqa: E501
        :type within_domain: bool
        :param has_exact_matches: The has_exact_matches of this ExactMatchResponse.  # noqa: E501
        :type has_exact_matches: List[str]
        """
        self.swagger_types = {
            'id': str,
            'within_domain': bool,
            'has_exact_matches': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'within_domain': 'within_domain',
            'has_exact_matches': 'has_exact_matches'
        }

        self._id = id
        self._within_domain = within_domain
        self._has_exact_matches = has_exact_matches

    @classmethod
    def from_dict(cls, dikt) -> 'ExactMatchResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExactMatchResponse of this ExactMatchResponse.  # noqa: E501
        :rtype: ExactMatchResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ExactMatchResponse.

        A given [CURIE](https://www.w3.org/TR/curie/) identifier.   # noqa: E501

        :return: The id of this ExactMatchResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ExactMatchResponse.

        A given [CURIE](https://www.w3.org/TR/curie/) identifier.   # noqa: E501

        :param id: The id of this ExactMatchResponse.
        :type id: str
        """

        self._id = id

    @property
    def within_domain(self) -> bool:
        """Gets the within_domain of this ExactMatchResponse.

        True if the knowledge source is aware of this identifier, and has the capacity to return the identified concept. Otherwise, false.   # noqa: E501

        :return: The within_domain of this ExactMatchResponse.
        :rtype: bool
        """
        return self._within_domain

    @within_domain.setter
    def within_domain(self, within_domain: bool):
        """Sets the within_domain of this ExactMatchResponse.

        True if the knowledge source is aware of this identifier, and has the capacity to return the identified concept. Otherwise, false.   # noqa: E501

        :param within_domain: The within_domain of this ExactMatchResponse.
        :type within_domain: bool
        """

        self._within_domain = within_domain

    @property
    def has_exact_matches(self) -> List[str]:
        """Gets the has_exact_matches of this ExactMatchResponse.

        List of [CURIE](https://www.w3.org/TR/curie/) identifiers of a exactly matching concepts.   # noqa: E501

        :return: The has_exact_matches of this ExactMatchResponse.
        :rtype: List[str]
        """
        return self._has_exact_matches

    @has_exact_matches.setter
    def has_exact_matches(self, has_exact_matches: List[str]):
        """Sets the has_exact_matches of this ExactMatchResponse.

        List of [CURIE](https://www.w3.org/TR/curie/) identifiers of a exactly matching concepts.   # noqa: E501

        :param has_exact_matches: The has_exact_matches of this ExactMatchResponse.
        :type has_exact_matches: List[str]
        """

        self._has_exact_matches = has_exact_matches
